# Here we will have our hardcoded variables/parameters
data_source:
  raw_path: "./data/raw/raw_data.json"  # Relative or absolute path to data file
  processed_path: "./data/processed/output.csv"  # Path to save processed data
  type: "csv"                      # Data file type: 'csv' or 'excel'
  sheet_name: "Sheet1"             # Only used if type == 'excel'
  delimiter: ","                   # Only used if type == 'csv'
  header: 0                        # Row number to use as column names (0-indexed), update if needed
  index: False
  encoding: "utf-8"                # File encoding (utf-8 covers most cases)

api_information:
  base_url: "https://backend.simfin.com/api/v3/companies"
  endpoint: "/prices/compact"
  headers:
    accept: "application/json"

logging:
  level: "INFO"                         # Logging level: DEBUG (verbose), INFO (default), WARNING, ERROR, CRITICAL
  log_file: "logs/main.log"          # File path for log output
  format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"  # Log message format
  datefmt: "%Y-%m-%d %H:%M:%S"          # Date format for logs
  
companies:
  - name: "Nvidia"
    ticker: "NVDA"
  - name: "Apple Inc."
    ticker: "AAPL"
  - name: "Microsoft"
    ticker: "MSFT"
  - name: "Amazon"
    ticker: "MSFT"
  - name: "Meta Platforms"
    ticker: "META"
  - name: "Alphabet Inc. (Class C)"
    ticker: "GOOG"
  - name: "Tesla, Inc."
    ticker: "TSLA"
  - name: "Walmart"
    ticker: "WMT"
  - name: "JPMorgan Chase"
    ticker: "JPM"
  - name: "Oracle Corporation"
    ticker: "ORCL"
  - name: "Visa Inc."
    ticker: "V"
  - name: "Mastercard"
    ticker: "MA"
  - name: "Netflix"
    ticker: "NFLX"
  - name: "ExxonMobil"
    ticker: "XOM"
  - name: "Johnson & Johnson"
    ticker: "JNJ"
  - name: "Palantir Technologies"
    ticker: "PLTR"
  - name: "Costco"
    ticker: "COST"
  - name: "Home Depot"
    ticker: "HD"
  - name: "Bank of America"
    ticker: "BAC"
  - name: "Procter & Gamble"
    ticker: "PG"
  - name: "Chevron Corporation"
    ticker: "CVX"
  - name: "Coca-Cola Company"
    ticker: "KO"
  - name: "Cisco"
    ticker: "CSCO"
  - name: "Wells Fargo"
    ticker: "WFC"
  - name: "IBM"
    ticker: "IBM"
  - name: "T-Mobile US"
    ticker: "TMUS"
  - name: "Morgan Stanley"
    ticker: "MS"
  - name: "Salesforce"
    ticker: "CRM"
  - name: "Caterpillar Inc."
    ticker: "CAT"
  - name: "American Express"
    ticker: "AXP"
  - name: "Philip Morris International"
    ticker: "PM"
  - name: "Goldman Sachs"
    ticker: "GS"
  - name: "RTX Corporation"
    ticker: "RTX"
  - name: "Abbott Laboratories"
    ticker: "ABT"
  - name: "McDonald's"
    ticker: "MCD"
  - name: "PepsiCo"
    ticker: "PEP"
  - name: "Walt Disney Company"
    ticker: "DIS"
  - name: "ServiceNow"
    ticker: "NOW"
  - name: "AT&T"
    ticker: "T"
  - name: "Intel"
    ticker: "INTC"
